language: cpp
compiler: 
 - gcc
 - clang
# Courtesy of http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11
before_install:
 - export ARTIFACTS=$(pwd)
 - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
 - sudo apt-get update -qq
 # Install Coveralls
 - sudo pip install cpp-coveralls
install:
 - chmod u+x install.sh
 - ./install.sh
os: 
 - linux
 - osx
script: make
after_success:
 - if [ "$CXX" == "g++" ]; then coveralls; fi